### ISSUE TITLE
ico & folder question

### ISSUE THREAD

**Issue by Begalov** [rmrevin/yii2-favicon-widget#4]
Хочу узнать, по какой из причин формат ico не реализован ?
И почему всё в корне хранится, а не, к примеру в рантайме с ассетами?

**Comment by rmrevin** [comment]
@KUbo0 а для чего поддерживать ico? Он нужен только для старых браузеров. Их это расширение не поддерживает.
А webroot используется для обратной совместимости. Если favicon.png уже лежит в webroot, достаточно в шаблон добавить `rmrevin\yii\favicon::widget()`.

**Comment by Begalov** [comment]
Ясно, так и полагал, большое спасибо за виджет!

**Comment by rmrevin** [comment]
Я рад, что смог принести пользу )

**Comment by Begalov** [comment]
Понравилась организация в тестовой версии сбербанка 
<img src="http://www.pixic.ru/i/V0O16392F982P0J7.png" border=0><br/>&nbsp;<br/>

**Comment by rmrevin** [comment]
@KUbo0 Вы без проблем сможете доработать виджет самостоятельно и прислать pull request, если потребуется. Спасибо )
