### ISSUE TITLE
Class 'Imagine\Image\Color' not found

### ISSUE THREAD

**Issue by stasionok** [rmrevin/yii2-favicon-widget#5]
yiisoft/yii2                                  dev-master c115738   Yii PHP Framework Version 2
yiisoft/yii2-imagine                          dev-master d3afd7c   The Imagine integration for the Yii framework
rmrevin/yii2-favicon-widget                   1.1.0                Favicon widget for Yii2

 in /vendor/rmrevin/yii2-favicon-widget/Favicon.php:265

thx

**Comment by rmrevin** [comment]
Update you ext `yii2-favicon-widget` to version `1.2`

**Comment by stasionok** [comment]
Thx, may be update README.md will help to avoid similar issues =)
